"""initial schema

Revision ID: 09446b55cadc
Revises:
Create Date: 2026-07-31 23:50:57.131388
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "09446b55cadc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.String(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("before_state", sa.JSON(), nullable=True),
        sa.Column("after_state", sa.JSON(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_audit_logs_actor_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        op.f("ix_audit_logs_actor_user_id"), "audit_logs", ["actor_user_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_table(
        "knowledge_spaces",
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("stable_key", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("target_audience", sa.Text(), nullable=False),
        sa.Column("scope_included", sa.JSON(), nullable=False),
        sa.Column("scope_excluded", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_knowledge_spaces_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_knowledge_spaces_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_spaces")),
        sa.UniqueConstraint("owner_id", "stable_key", name=op.f("uq_knowledge_spaces_owner_id")),
    )
    op.create_index(
        op.f("ix_knowledge_spaces_created_by"), "knowledge_spaces", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_spaces_owner_id"), "knowledge_spaces", ["owner_id"], unique=False
    )
    op.create_table(
        "ai_suggestions",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("space_id", sa.String(), nullable=True),
        sa.Column("suggestion_type", sa.String(length=40), nullable=False),
        sa.Column("target_type", sa.String(length=40), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=160), nullable=False),
        sa.Column("prompt_version", sa.String(length=80), nullable=False),
        sa.Column("raw_structured_output", sa.JSON(), nullable=False),
        sa.Column("proposed_changes", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("reviewed_by", sa.String(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("accepted_changes", sa.JSON(), nullable=True),
        sa.Column("reverted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ai_suggestions_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_ai_suggestions_reviewed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["knowledge_spaces.id"],
            name=op.f("fk_ai_suggestions_space_id_knowledge_spaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_suggestions")),
    )
    op.create_index(
        op.f("ix_ai_suggestions_space_id"), "ai_suggestions", ["space_id"], unique=False
    )
    op.create_index(op.f("ix_ai_suggestions_user_id"), "ai_suggestions", ["user_id"], unique=False)
    op.create_table(
        "knowledge_map_versions",
        sa.Column("space_id", sa.String(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("change_summary", sa.Text(), nullable=False),
        sa.Column("parent_version_id", sa.String(), nullable=True),
        sa.Column("schema_version", sa.String(length=50), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_by", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.CheckConstraint(
            "version_number >= 1", name=op.f("ck_knowledge_map_versions_version_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_knowledge_map_versions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["parent_version_id"],
            ["knowledge_map_versions.id"],
            name=op.f("fk_knowledge_map_versions_parent_version_id_knowledge_map_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["users.id"],
            name=op.f("fk_knowledge_map_versions_published_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["knowledge_spaces.id"],
            name=op.f("fk_knowledge_map_versions_space_id_knowledge_spaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_map_versions")),
        sa.UniqueConstraint(
            "space_id", "version_number", name=op.f("uq_knowledge_map_versions_space_id")
        ),
    )
    op.create_index(
        op.f("ix_knowledge_map_versions_space_id"),
        "knowledge_map_versions",
        ["space_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_nodes",
        sa.Column("space_id", sa.String(), nullable=False),
        sa.Column("stable_key", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("node_type", sa.String(length=24), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("depth_level", sa.Integer(), nullable=False),
        sa.Column("learning_objectives", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("manually_locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("depth_level >= 0", name=op.f("ck_knowledge_nodes_depth_nonnegative")),
        sa.CheckConstraint(
            "difficulty BETWEEN 1 AND 5", name=op.f("ck_knowledge_nodes_difficulty_range")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_knowledge_nodes_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["knowledge_spaces.id"],
            name=op.f("fk_knowledge_nodes_space_id_knowledge_spaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_nodes")),
        sa.UniqueConstraint("space_id", "stable_key", name=op.f("uq_knowledge_nodes_space_id")),
    )
    op.create_index(
        op.f("ix_knowledge_nodes_space_id"), "knowledge_nodes", ["space_id"], unique=False
    )
    op.create_table(
        "assessments",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("rubric", sa.JSON(), nullable=False),
        sa.Column("max_score", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_assessments_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["node_id"], ["knowledge_nodes.id"], name=op.f("fk_assessments_node_id_knowledge_nodes")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessments")),
    )
    op.create_index(op.f("ix_assessments_node_id"), "assessments", ["node_id"], unique=False)
    op.create_table(
        "knowledge_edges",
        sa.Column("space_id", sa.String(), nullable=False),
        sa.Column("map_version_id", sa.String(), nullable=False),
        sa.Column("source_node_id", sa.String(), nullable=False),
        sa.Column("target_node_id", sa.String(), nullable=False),
        sa.Column("relation_type", sa.String(length=24), nullable=False),
        sa.Column("strength", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("required_mastery_level", sa.Integer(), nullable=False),
        sa.Column("is_hard_requirement", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("source_reference", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("manually_locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "relation_type = 'PREREQUISITE' OR (is_hard_requirement = false AND required_mastery_level = 0)",
            name=op.f("ck_knowledge_edges_requirements_only_on_prerequisite"),
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_knowledge_edges_confidence_range")
        ),
        sa.CheckConstraint(
            "required_mastery_level BETWEEN 0 AND 5",
            name=op.f("ck_knowledge_edges_required_mastery_range"),
        ),
        sa.CheckConstraint(
            "source_node_id <> target_node_id", name=op.f("ck_knowledge_edges_no_self_edge")
        ),
        sa.CheckConstraint(
            "strength BETWEEN 0 AND 1", name=op.f("ck_knowledge_edges_strength_range")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_knowledge_edges_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["map_version_id"],
            ["knowledge_map_versions.id"],
            name=op.f("fk_knowledge_edges_map_version_id_knowledge_map_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["source_node_id"],
            ["knowledge_nodes.id"],
            name=op.f("fk_knowledge_edges_source_node_id_knowledge_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["knowledge_spaces.id"],
            name=op.f("fk_knowledge_edges_space_id_knowledge_spaces"),
        ),
        sa.ForeignKeyConstraint(
            ["target_node_id"],
            ["knowledge_nodes.id"],
            name=op.f("fk_knowledge_edges_target_node_id_knowledge_nodes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_edges")),
        sa.UniqueConstraint(
            "map_version_id",
            "source_node_id",
            "target_node_id",
            "relation_type",
            name=op.f("uq_knowledge_edges_map_version_id"),
        ),
    )
    op.create_index(
        op.f("ix_knowledge_edges_map_version_id"),
        "knowledge_edges",
        ["map_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_edges_source_node_id"),
        "knowledge_edges",
        ["source_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_edges_space_id"), "knowledge_edges", ["space_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_edges_target_node_id"),
        "knowledge_edges",
        ["target_node_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_node_versions",
        sa.Column("space_id", sa.String(), nullable=False),
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("map_version_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("node_type", sa.String(length=24), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("depth_level", sa.Integer(), nullable=False),
        sa.Column("learning_objectives", sa.JSON(), nullable=False),
        sa.Column("source_basis", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("change_source", sa.String(length=30), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.CheckConstraint(
            "depth_level >= 0", name=op.f("ck_knowledge_node_versions_depth_nonnegative")
        ),
        sa.CheckConstraint(
            "difficulty BETWEEN 1 AND 5", name=op.f("ck_knowledge_node_versions_difficulty_range")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_knowledge_node_versions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["map_version_id"],
            ["knowledge_map_versions.id"],
            name=op.f("fk_knowledge_node_versions_map_version_id_knowledge_map_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["knowledge_nodes.id"],
            name=op.f("fk_knowledge_node_versions_node_id_knowledge_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["knowledge_spaces.id"],
            name=op.f("fk_knowledge_node_versions_space_id_knowledge_spaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_node_versions")),
        sa.UniqueConstraint(
            "node_id", "map_version_id", name=op.f("uq_knowledge_node_versions_node_id")
        ),
    )
    op.create_index(
        op.f("ix_knowledge_node_versions_map_version_id"),
        "knowledge_node_versions",
        ["map_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_node_versions_node_id"),
        "knowledge_node_versions",
        ["node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_node_versions_space_id"),
        "knowledge_node_versions",
        ["space_id"],
        unique=False,
    )
    op.create_table(
        "learner_node_states",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("mastery_level", sa.Integer(), nullable=False),
        sa.Column("mastery_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("numeric_evidence_count", sa.Integer(), nullable=False),
        sa.Column("last_studied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_review_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state_source", sa.String(length=32), nullable=False),
        sa.Column("manually_overridden", sa.Boolean(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=80), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_learner_node_states_confidence_range")
        ),
        sa.CheckConstraint(
            "mastery_level BETWEEN 0 AND 5", name=op.f("ck_learner_node_states_mastery_level_range")
        ),
        sa.CheckConstraint(
            "mastery_score BETWEEN 0 AND 1", name=op.f("ck_learner_node_states_mastery_score_range")
        ),
        sa.CheckConstraint(
            "numeric_evidence_count >= 0",
            name=op.f("ck_learner_node_states_numeric_evidence_count_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["knowledge_nodes.id"],
            name=op.f("fk_learner_node_states_node_id_knowledge_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_learner_node_states_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learner_node_states")),
        sa.UniqueConstraint("user_id", "node_id", name=op.f("uq_learner_node_states_user_id")),
    )
    op.create_index(
        op.f("ix_learner_node_states_node_id"), "learner_node_states", ["node_id"], unique=False
    )
    op.create_index(
        op.f("ix_learner_node_states_user_id"), "learner_node_states", ["user_id"], unique=False
    )
    op.create_table(
        "learning_goals",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("space_id", sa.String(), nullable=False),
        sa.Column("target_node_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("target_mastery_level", sa.Integer(), nullable=False),
        sa.Column("route_preference", sa.String(length=32), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("load_preference", sa.String(length=120), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "target_mastery_level BETWEEN 0 AND 5",
            name=op.f("ck_learning_goals_target_mastery_range"),
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["knowledge_spaces.id"],
            name=op.f("fk_learning_goals_space_id_knowledge_spaces"),
        ),
        sa.ForeignKeyConstraint(
            ["target_node_id"],
            ["knowledge_nodes.id"],
            name=op.f("fk_learning_goals_target_node_id_knowledge_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_learning_goals_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_goals")),
    )
    op.create_index(
        op.f("ix_learning_goals_space_id"), "learning_goals", ["space_id"], unique=False
    )
    op.create_index(
        op.f("ix_learning_goals_target_node_id"), "learning_goals", ["target_node_id"], unique=False
    )
    op.create_index(op.f("ix_learning_goals_user_id"), "learning_goals", ["user_id"], unique=False)
    op.create_table(
        "learning_resources",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("resource_type", sa.String(length=40), nullable=False),
        sa.Column("uri", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source_reference", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_learning_resources_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["knowledge_nodes.id"],
            name=op.f("fk_learning_resources_node_id_knowledge_nodes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_resources")),
    )
    op.create_index(
        op.f("ix_learning_resources_node_id"), "learning_resources", ["node_id"], unique=False
    )
    op.create_table(
        "learning_sessions",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resource_ids", sa.JSON(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("difficulties", sa.Text(), nullable=True),
        sa.Column("self_rating", sa.Integer(), nullable=True),
        sa.Column("next_step", sa.Text(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["knowledge_nodes.id"],
            name=op.f("fk_learning_sessions_node_id_knowledge_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_learning_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_sessions")),
    )
    op.create_index(
        op.f("ix_learning_sessions_node_id"), "learning_sessions", ["node_id"], unique=False
    )
    op.create_index(
        op.f("ix_learning_sessions_user_id"), "learning_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "assessment_attempts",
        sa.Column("assessment_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.String(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_assessment_attempts_assessment_id_assessments"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_assessment_attempts_reviewed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_assessment_attempts_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_attempts")),
    )
    op.create_index(
        op.f("ix_assessment_attempts_assessment_id"),
        "assessment_attempts",
        ["assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_attempts_user_id"), "assessment_attempts", ["user_id"], unique=False
    )
    op.create_table(
        "learning_evidence",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("evidence_type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("artifact_url", sa.Text(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("reviewed_by", sa.String(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["knowledge_nodes.id"],
            name=op.f("fk_learning_evidence_node_id_knowledge_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_learning_evidence_reviewed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["learning_sessions.id"],
            name=op.f("fk_learning_evidence_session_id_learning_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_learning_evidence_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_evidence")),
    )
    op.create_index(
        op.f("ix_learning_evidence_node_id"), "learning_evidence", ["node_id"], unique=False
    )
    op.create_index(
        op.f("ix_learning_evidence_session_id"), "learning_evidence", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_learning_evidence_user_id"), "learning_evidence", ["user_id"], unique=False
    )
    op.create_table(
        "learning_paths",
        sa.Column("goal_id", sa.String(), nullable=False),
        sa.Column("space_id", sa.String(), nullable=False),
        sa.Column("map_version_id", sa.String(), nullable=False),
        sa.Column("generation_number", sa.Integer(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("preference_snapshot", sa.JSON(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["learning_goals.id"],
            name=op.f("fk_learning_paths_goal_id_learning_goals"),
        ),
        sa.ForeignKeyConstraint(
            ["map_version_id"],
            ["knowledge_map_versions.id"],
            name=op.f("fk_learning_paths_map_version_id_knowledge_map_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["knowledge_spaces.id"],
            name=op.f("fk_learning_paths_space_id_knowledge_spaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_paths")),
    )
    op.create_index(op.f("ix_learning_paths_goal_id"), "learning_paths", ["goal_id"], unique=False)
    op.create_index(
        op.f("ix_learning_paths_map_version_id"), "learning_paths", ["map_version_id"], unique=False
    )
    op.create_table(
        "learning_path_nodes",
        sa.Column("path_id", sa.String(), nullable=False),
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("required_mastery_level", sa.Integer(), nullable=False),
        sa.Column("recommendation_reason", sa.Text(), nullable=False),
        sa.Column("satisfied_prerequisites", sa.JSON(), nullable=False),
        sa.Column("unmet_prerequisites", sa.JSON(), nullable=False),
        sa.Column("unlocks", sa.JSON(), nullable=False),
        sa.Column("computed_status", sa.String(length=24), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.CheckConstraint(
            "required_mastery_level BETWEEN 0 AND 5",
            name=op.f("ck_learning_path_nodes_required_mastery_range"),
        ),
        sa.CheckConstraint(
            "sequence_number >= 0", name=op.f("ck_learning_path_nodes_sequence_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["knowledge_nodes.id"],
            name=op.f("fk_learning_path_nodes_node_id_knowledge_nodes"),
        ),
        sa.ForeignKeyConstraint(
            ["path_id"],
            ["learning_paths.id"],
            name=op.f("fk_learning_path_nodes_path_id_learning_paths"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_path_nodes")),
        sa.UniqueConstraint("path_id", "node_id", name=op.f("uq_learning_path_nodes_path_id")),
        sa.UniqueConstraint(
            "path_id", "sequence_number", name=op.f("uq_learning_path_nodes_path_id")
        ),
    )
    op.create_index(
        op.f("ix_learning_path_nodes_path_id"), "learning_path_nodes", ["path_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_learning_path_nodes_path_id"), table_name="learning_path_nodes")
    op.drop_table("learning_path_nodes")
    op.drop_index(op.f("ix_learning_paths_map_version_id"), table_name="learning_paths")
    op.drop_index(op.f("ix_learning_paths_goal_id"), table_name="learning_paths")
    op.drop_table("learning_paths")
    op.drop_index(op.f("ix_learning_evidence_user_id"), table_name="learning_evidence")
    op.drop_index(op.f("ix_learning_evidence_session_id"), table_name="learning_evidence")
    op.drop_index(op.f("ix_learning_evidence_node_id"), table_name="learning_evidence")
    op.drop_table("learning_evidence")
    op.drop_index(op.f("ix_assessment_attempts_user_id"), table_name="assessment_attempts")
    op.drop_index(op.f("ix_assessment_attempts_assessment_id"), table_name="assessment_attempts")
    op.drop_table("assessment_attempts")
    op.drop_index(op.f("ix_learning_sessions_user_id"), table_name="learning_sessions")
    op.drop_index(op.f("ix_learning_sessions_node_id"), table_name="learning_sessions")
    op.drop_table("learning_sessions")
    op.drop_index(op.f("ix_learning_resources_node_id"), table_name="learning_resources")
    op.drop_table("learning_resources")
    op.drop_index(op.f("ix_learning_goals_user_id"), table_name="learning_goals")
    op.drop_index(op.f("ix_learning_goals_target_node_id"), table_name="learning_goals")
    op.drop_index(op.f("ix_learning_goals_space_id"), table_name="learning_goals")
    op.drop_table("learning_goals")
    op.drop_index(op.f("ix_learner_node_states_user_id"), table_name="learner_node_states")
    op.drop_index(op.f("ix_learner_node_states_node_id"), table_name="learner_node_states")
    op.drop_table("learner_node_states")
    op.drop_index(op.f("ix_knowledge_node_versions_space_id"), table_name="knowledge_node_versions")
    op.drop_index(op.f("ix_knowledge_node_versions_node_id"), table_name="knowledge_node_versions")
    op.drop_index(
        op.f("ix_knowledge_node_versions_map_version_id"), table_name="knowledge_node_versions"
    )
    op.drop_table("knowledge_node_versions")
    op.drop_index(op.f("ix_knowledge_edges_target_node_id"), table_name="knowledge_edges")
    op.drop_index(op.f("ix_knowledge_edges_space_id"), table_name="knowledge_edges")
    op.drop_index(op.f("ix_knowledge_edges_source_node_id"), table_name="knowledge_edges")
    op.drop_index(op.f("ix_knowledge_edges_map_version_id"), table_name="knowledge_edges")
    op.drop_table("knowledge_edges")
    op.drop_index(op.f("ix_assessments_node_id"), table_name="assessments")
    op.drop_table("assessments")
    op.drop_index(op.f("ix_knowledge_nodes_space_id"), table_name="knowledge_nodes")
    op.drop_table("knowledge_nodes")
    op.drop_index(op.f("ix_knowledge_map_versions_space_id"), table_name="knowledge_map_versions")
    op.drop_table("knowledge_map_versions")
    op.drop_index(op.f("ix_ai_suggestions_user_id"), table_name="ai_suggestions")
    op.drop_index(op.f("ix_ai_suggestions_space_id"), table_name="ai_suggestions")
    op.drop_table("ai_suggestions")
    op.drop_index(op.f("ix_knowledge_spaces_owner_id"), table_name="knowledge_spaces")
    op.drop_index(op.f("ix_knowledge_spaces_created_by"), table_name="knowledge_spaces")
    op.drop_table("knowledge_spaces")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_user_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("users")
    # ### end Alembic commands ###
